
[build]
builder = "NIXPACKS"
watchPatterns = ["src/**"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"

[[services]]
name = "web"
healthPath = "/"
healthTimeout = 300
healthInterval = 30
