
[build]
builder = "NIXPACKS"
nixpacksVersion = "1.11.0"
buildCommand = "npm run build"
watchPatterns = ["src/**", "public/**", "index.html", "vite.config.ts"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 60
sleepApplication = false

[service]
autoStart = true

[env]
NODE_ENV = "production"
VITE_PUBLIC_URL = "${RAILWAY_STATIC_URL}"

# Make sure environment variables from Railway Secrets are available
VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
VITE_FLOWISE_URL = "${VITE_FLOWISE_URL}"
VITE_FLOWISE_API_KEY = "${VITE_FLOWISE_API_KEY}"

[[ports]]
port = "8080"
internal = false
protocol = "HTTP"

[[statics]]
source = "/dist"
destination = "/"
