
[build]
builder = "NIXPACKS"
nixpacksVersion = "1.11.0"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"

[service]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
