
# Railway configuration for PT2030 Candidaturas app

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = [
  "/src/**",
  "package.json"
]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1
sleepApplication = false

[variables]
VITE_SUPABASE_URL = "${SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
VITE_FLOWISE_URL = "${FLOWISE_URL}"
VITE_FLOWISE_API_KEY = "${FLOWISE_API_KEY}"
PORT = "3000"

[phases.setup]
nixPkgsFile = "nixpkgs.json"

[[services]]
autoDeploy = true
name = "pt2030-app"
envVarValueFromKey = { SUPABASE_URL = "SUPABASE_URL", SUPABASE_ANON_KEY = "SUPABASE_ANON_KEY" }
